[package]
name = "example"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.1"
imgui-sdl2 = "0.4.0"
imgui-opengl-renderer = "0.3.2"
gl = "0.11.0"

imgui = "0.0.21"
imgui-ext = { path = "../" }