[package]
name = "example"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
sdl2 = { version = "0.32.1", optional = true }
imgui-sdl2 = { version = "0.4.0", optional = true }
imgui-opengl-renderer = { version = "0.3.2", optional = true }
gl = { version = "0.11.0", optional = true }

imgui = "0.0.21"
imgui-ext = { path = "../" }

[features]
default = ["sdl"]
sdl = ["sdl2", "imgui-sdl2", "imgui-opengl-renderer", "gl"]
ci = []