language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
after_success:
- test $TRAVIS_BRANCH = "stabilize" && bash ci/publish_docs.sh