[package]
name = "imgui_ext"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"

[workspace]
members = ["imgui_derive", "example"]

[dependencies]
imgui = "*"
imgui_ext_derive = { path = "imgui_derive" }
