[package]
name = "imgui-ext"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"
description = "Define imgui UIs using a derive macro."
repository = "https://github.com/germangb/imgui-ext"
readme = "README.md"
keywords = ["gui", "imgui", "macro"]
categories = ["gui", "api-bindings", "game-engines"]
license = "MIT"
exclude = ["ci/*"]

[badges]
travis-ci = { repository = "germangb/imgui-ext", branch = "master" }

[workspace]
members = ["imgui_derive", "example"]

[dependencies]
imgui = "^0.0"
imgui-ext-derive = { version = "0.1.0", path = "imgui_derive" }
