[package]
name = "imgui_ext"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"

[workspace]
members = ["modules/derive", "modules/traits", "example"]

[dependencies]
imgui = "*"
imgui_ext_derive = { path = "modules/derive" }
imgui_ext_traits = { path = "modules/traits" }
