[package]
name = "imgui-ext-derive"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15.18", features = ["derive"]}
quote = "0.6.9"
proc-macro2 = "0.4.20"
